FROM node:22-alpine

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate

COPY pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps/frontend/package.json ./apps/frontend/
COPY package.json ./

RUN pnpm install --filter=frontend --frozen-lockfile

WORKDIR /app/apps/frontend

EXPOSE 5173

CMD ["sh", "-c", "pnpm install --filter=frontend && pnpm dev --host"]
