FROM node:22-alpine

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate

COPY pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps/backend/package.json ./apps/backend/
COPY package.json ./

RUN pnpm install --filter=backend --frozen-lockfile

WORKDIR /app/apps/backend

EXPOSE 3000

CMD ["pnpm", "dev"]
